### ISSUE TITLE
Add RedHat/CentOS Support

### ISSUE THREAD

**Issue by PrymalInstynct** [sbaerlocher/ansible.telegraf#6]
```
---
# tasks file for sbaerlocher.telegraf

- name: 'red hat : install YUM repository'
  become: true
  yum_repository:
    name: influxdb-stable
    description: Stable InfluxDB YUM Repository
    baseurl: https://repos.influxdata.com/rhel/$releasever/$basearch/stable
    gpgkey: https://repos.influxdata.com/influxdb.key
    gpgcheck: yes
    enabled: yes

- name: 'red hat : Install Telegraf package'
  become: true
  yum:
    name: '{{ telegraf_package }}'
    state: latest
  register: register_telegraf_package_installed
  until: register_telegraf_package_installed is succeeded
  notify: 'Restart Telegraf'

- name: 'red hat : include configuration tasks'
  include_tasks: 'Linux/configuration.yml'
```
